/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hanse
 */
public class ListaDeOrdenes extends javax.swing.JFrame {

       ConexionBD cc=new ConexionBD();
           // volvemos a crear una variable tipo connection que recibira el valor del metodo conexion y se alamcena en la variable cn
           Connection cn=cc.conexion();
           
           public String placa, tipo, idcliente, nombre, telefono, correo, tiposervicio;

    
    public ListaDeOrdenes() {
        initComponents();
             // para actualizar los datos activos
             mostrarDatos("");
    }
    
    public String getPlaca() {
        return placa;
    }

    public void setPlaca(String placa) {
        this.placa = placa;
    }
    
           public void mostrarDatos(String valor) {
          
               // para darle forma o modelo a la tabla
               DefaultTableModel modelo = new DefaultTableModel();
               modelo.addColumn("Placa");
               modelo.addColumn("Vehiculo");
               modelo.addColumn("id Cliente");
               modelo.addColumn("Nombre Cliente");
               modelo.addColumn("Telefono");
               modelo.addColumn("Correo");
               modelo.addColumn("Servicio");
               jtOrdenesDeTrabajo.setModel(modelo);
               // para poder almacenar los datos en la tabla
               String datos[] = new String [7];
               
               // variable del nombre de la tabla
               String sql = "";
               if(valor.equals("")){
                   // aca muestra todos los valores
                   sql="SELECT * FROM orden_de_trabajo WHERE estado_orden = 'Activa'";
               }else{
                   // aqui solo muestra el buscado con WHERE
                   // recordar si se puede hacer un swtch para poder buscar en toas las columnas
                   sql = "SELECT * FROM orden_de_trabajo WHERE Numero_de_placa = '"+ valor +"'";
               }
               
                
                try {
                    
               Statement st = cn.createStatement();
               // el result set alamecena los valores de la consulta a realizar
               ResultSet rs = st.executeQuery(sql);
               
               // MOSTRAR LOS DATOS EN LA TABLA y el next saber si recorrio todas las filas
               while(rs.next()){
                    // hacer esto con un for para ser más facil
                    for (int i = 0; i < datos.length; i++) {
                       datos[i] = rs.getString(i+1);
                   }
                   modelo.addRow(datos);
               }
               
               jtOrdenesDeTrabajo.setModel(modelo);
               
           } catch (SQLException ex) {
                    System.err.println(ex.toString());
           }
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbAgregarOrden = new javax.swing.JButton();
        jbEliminarLista = new javax.swing.JButton();
        jbModificarLista = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtOrdenesDeTrabajo = new javax.swing.JTable();
        jtfBuscar = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbAgregarOrden.setText("Agregar");
        jbAgregarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarOrdenActionPerformed(evt);
            }
        });

        jbEliminarLista.setText("Eliminar");
        jbEliminarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarListaActionPerformed(evt);
            }
        });

        jbModificarLista.setText("Modificar");
        jbModificarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarListaActionPerformed(evt);
            }
        });

        jtOrdenesDeTrabajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtOrdenesDeTrabajo);

        jScrollPane2.setViewportView(jScrollPane1);

        jtfBuscar.setText("Numero de placa");
        jtfBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfBuscarMouseClicked(evt);
            }
        });
        jtfBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfBuscarActionPerformed(evt);
            }
        });
        jtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarKeyTyped(evt);
            }
        });

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbMostrar.setText("Mostrar todos");
        jbMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbBuscar)
                .addGap(40, 40, 40)
                .addComponent(jbMostrar)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jbAgregarOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbModificarLista)
                .addGap(171, 171, 171)
                .addComponent(jbEliminarLista)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscar)
                    .addComponent(jbMostrar))
                .addGap(89, 89, 89)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarOrden)
                    .addComponent(jbEliminarLista)
                    .addComponent(jbModificarLista))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarKeyTyped

        // se asegura de capturar la tecla enter y descarta las demas
        char teclaPresionada = evt.getKeyChar();

        // si detecta la tecla enter activa el boton buscar
        if(teclaPresionada == KeyEvent.VK_ENTER){
            jbBuscar.doClick();
        }

    }//GEN-LAST:event_jtfBuscarKeyTyped

    private void jtfBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfBuscarActionPerformed

    }//GEN-LAST:event_jtfBuscarActionPerformed

    private void jtfBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfBuscarMouseClicked
        jtfBuscar.setText("");
    }//GEN-LAST:event_jtfBuscarMouseClicked

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // le asignamos a la variable valor el valor de la caja de texto buscar
        mostrarDatos(jtfBuscar.getText());

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMostrarActionPerformed

        mostrarDatos("");

    }//GEN-LAST:event_jbMostrarActionPerformed

    private void jbAgregarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarOrdenActionPerformed

        OrdenDeTrabajo ot = new OrdenDeTrabajo ();
        // se hace visible el orden de trabajo
        ot.setVisible(true);
        // se cierra la tabla de orden de trabajo
        dispose();

    }//GEN-LAST:event_jbAgregarOrdenActionPerformed

    private void jbModificarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarListaActionPerformed

        // vamos a mostrar los datos de la fila selccionada
        int fila = jtOrdenesDeTrabajo.getSelectedRow();

        if (fila>=0){
            //Hacemos visible el frame paea modificar
           ModificarOrden mo = new ModificarOrden();
           
           // mandar los valores de la tabla a las cajas de texto
            placa= jtOrdenesDeTrabajo.getValueAt(fila, 0).toString();
            tipo= jtOrdenesDeTrabajo.getValueAt(fila, 1).toString();
            idcliente = jtOrdenesDeTrabajo.getValueAt(fila, 2).toString();
            nombre = jtOrdenesDeTrabajo.getValueAt(fila, 3).toString();
            telefono = jtOrdenesDeTrabajo.getValueAt(fila, 4).toString();
            correo = jtOrdenesDeTrabajo.getValueAt(fila, 5).toString();
            tiposervicio = jtOrdenesDeTrabajo.getValueAt(fila, 6).toString();
            mo.setDatos(placa, tipo,idcliente, nombre, telefono, correo, tiposervicio);
            mo.setVisible(true);
            
        }
        else{
            JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna orden de trabajo, porfavor seleccione una orden de trabajo de la tabla.");
        }

    }//GEN-LAST:event_jbModificarListaActionPerformed

    private void jbEliminarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarListaActionPerformed
        // le asignamos el valor de la fila seleccionada a la variable fila
        // para saber si hemos seleccionado algo de la tabla
        int fila = jtOrdenesDeTrabajo.getSelectedRow();
        
        if(fila>= 0){
            
            try {
                //con esto vamos a eliminar el registro seleccionado                                                                 nombre de la tabla                                                          
                PreparedStatement pst = cn.prepareStatement("DELETE FROM orden_de_trabajo WHERE Numero_de_placa ='"+jtOrdenesDeTrabajo.getValueAt(fila, 0).toString()+"'");
                // para subir a la bd
                pst.executeUpdate();
                // actualizamos los datos
                mostrarDatos("");
                
            } catch (SQLException ex) {
                System.err.println(ex.toString());
            }
             
        }else{
            
           JOptionPane.showMessageDialog(null, "No ha seleccionado ninguna orden de trabajo, porfavor seleccione una orden de trabajo de la tabla."); 
        }
        
        
    }//GEN-LAST:event_jbEliminarListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeOrdenes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDeOrdenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAgregarOrden;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminarLista;
    private javax.swing.JButton jbModificarLista;
    private javax.swing.JButton jbMostrar;
    private javax.swing.JTable jtOrdenesDeTrabajo;
    private javax.swing.JTextField jtfBuscar;
    // End of variables declaration//GEN-END:variables
}
