/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import com.mysql.jdbc.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author hanse
 */
public class ModificarOrden extends javax.swing.JFrame {


    private String placa, tipo, idcliente, nombre, telefono, correo, tiposervicio;;
    
    public ModificarOrden() {
        initComponents();
    }

    // usar este metodo para recibir el valor de placa asignado en la lista de ordenes para ponerlo en los txt field de este jframe
        public void setDatos(String placa, String tipo, String idcliente, String nombre, String telefono, String correo, String tiposervicio) {
        this.placa = placa;
        this.tipo = tipo;
        this.idcliente = idcliente;
        this.nombre = nombre;
        this.telefono = telefono;
        this.correo = correo;
        this.tiposervicio = tiposervicio;
        
        // enviamos el registro al txt field
        jtfPlacaVehiculo.setText(placa);
        jcbTipoVehiculo.setSelectedItem(tipo);
        jtfIdCliente.setText(idcliente);
        jtfNombreCliente.setText(nombre);
        jtfTelefonoCliente.setText(telefono);
        jtfCorreoCliente.setText(correo);
        jcbTipoServicio.setSelectedItem(tiposervicio);
        
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfTelefonoCliente = new javax.swing.JTextField();
        jbGenerarOT = new javax.swing.JButton();
        jtfCorreoCliente = new javax.swing.JTextField();
        jcbTipoServicio = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfPlacaVehiculo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtfIdCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfNombreCliente = new javax.swing.JTextField();
        jbAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbGenerarOT.setText("Modificar orden de trabajo");
        jbGenerarOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarOTActionPerformed(evt);
            }
        });

        jcbTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Lavado", "Aspirado", "Encerado", "Lavado y apirado", "Lavado aspirado y encerado" }));

        jLabel7.setText("Tipo de servicio:");

        jLabel6.setText("Correo eléctronico de cliente:");

        jLabel5.setText("Teléfono de cliente:");

        jLabel4.setText("Nombre de cliente:");

        jtfPlacaVehiculo.setEnabled(false);

        jLabel3.setText("Identificación de cliente:");

        jcbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Sedan", "SUV", "4x4", "Motocicleta", "Camión" }));
        jcbTipoVehiculo.setToolTipText("");

        jLabel2.setText("Tipo de vehiculo:");

        jLabel1.setText("Número de placa de vehiculo:");

        jtfNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreClienteActionPerformed(evt);
            }
        });

        jbAtras.setText("Atrás");
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPlacaVehiculo)
                            .addComponent(jtfIdCliente)
                            .addComponent(jtfNombreCliente)
                            .addComponent(jtfTelefonoCliente)
                            .addComponent(jtfCorreoCliente)
                            .addComponent(jcbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbAtras))
                .addGap(0, 58, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jbGenerarOT)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbAtras)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(jbGenerarOT)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGenerarOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarOTActionPerformed

        ConexionBD cc=new ConexionBD();
        // volvemos a crear una variable tipo connection que recibira el valor del metodo conexion y se alamcena en la variable cn
        Connection cn=cc.conexion();

        try{
            // creamos una variable tipo prepared statement que almacenara un INSERT INTO que debera alamecenar datos
            // nombre de las columnas
            PreparedStatement pst = cn.prepareStatement("UPDATE orden_de_trabajo SET tipo_vehiculo = '"+jcbTipoVehiculo.getSelectedItem()+"'"
                    + ", id_cliente = '"+jtfIdCliente.getText()+"'"
                    + ", nombe_cliente = '"+jtfNombreCliente.getText()+"'" 
                    + ", telefono_cliente = '"+jtfTelefonoCliente.getText()+"'"
                    + ", correo_cliente = '"+jtfCorreoCliente.getText()+"'"
                    + ", tipo_servicio = '"+jcbTipoServicio.getSelectedItem()+"'"
                    + "WHERE Numero_de_placa ='"+jtfPlacaVehiculo.getText()+"'");
            

            int a=pst.executeUpdate();

            if(a>0){

                JOptionPane.showMessageDialog(null,"Orden modificada con éxito");
                dispose();
                ListaDeOrdenes lo = new ListaDeOrdenes();
                lo.setVisible(true);

            }
            else{
                JOptionPane.showMessageDialog(null,"Error al modificar");
            }
        }catch(Exception e){
            System.err.println(e.toString());
        }        // TODO
    }//GEN-LAST:event_jbGenerarOTActionPerformed

    private void jtfNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreClienteActionPerformed

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed

        MenuPrincipal menu = new MenuPrincipal ();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarOrden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarOrden().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbGenerarOT;
    private javax.swing.JComboBox<String> jcbTipoServicio;
    private javax.swing.JComboBox<String> jcbTipoVehiculo;
    private javax.swing.JTextField jtfCorreoCliente;
    private javax.swing.JTextField jtfIdCliente;
    private javax.swing.JTextField jtfNombreCliente;
    private javax.swing.JTextField jtfPlacaVehiculo;
    private javax.swing.JTextField jtfTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
