/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectofinal;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author hanse
 */
public class OrdenDeTrabajo extends javax.swing.JFrame {

    /**
     * Creates new form OrdenDeTrabajo
     */
    public OrdenDeTrabajo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcbTipoVehiculo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfPlacaVehiculo = new javax.swing.JTextField();
        jtfIdCliente = new javax.swing.JTextField();
        jtfNombreCliente = new javax.swing.JTextField();
        jtfTelefonoCliente = new javax.swing.JTextField();
        jtfCorreoCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jcbTipoServicio = new javax.swing.JComboBox<>();
        jbGenerarOT = new javax.swing.JButton();
        jbAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("OrdenDeTrabajo"); // NOI18N

        jLabel1.setText("Número de placa de vehiculo:");

        jLabel2.setText("Tipo de vehiculo:");

        jLabel3.setText("Identificación de cliente:");

        jcbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Sedan", "SUV", "4x4", "Motocicleta", "Camión" }));
        jcbTipoVehiculo.setToolTipText("");

        jLabel4.setText("Nombre de cliente:");

        jLabel5.setText("Teléfono de cliente:");

        jLabel6.setText("Correo eléctronico de cliente:");

        jtfNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreClienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de servicio:");

        jcbTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Lavado", "Aspirado", "Encerado", "Lavado y apirado", "Lavado aspirado y encerado" }));

        jbGenerarOT.setText("Generar orden de trabajo");
        jbGenerarOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGenerarOTActionPerformed(evt);
            }
        });

        jbAtras.setText("Atrás");
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbTipoVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPlacaVehiculo)
                            .addComponent(jtfIdCliente)
                            .addComponent(jtfNombreCliente)
                            .addComponent(jtfTelefonoCliente)
                            .addComponent(jtfCorreoCliente)
                            .addComponent(jcbTipoServicio, 0, 350, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jbGenerarOT))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbAtras)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAtras)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtfIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jtfNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jbGenerarOT)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreClienteActionPerformed

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
       
        MenuPrincipal menu = new MenuPrincipal ();
        menu.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jbAtrasActionPerformed

    private void jbGenerarOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGenerarOTActionPerformed
        
        
           ConexionBD cc=new ConexionBD();
           // volvemos a crear una variable tipo connection que recibira el valor del metodo conexion y se alamcena en la variable cn
           Connection cn=cc.conexion();
           
        try{
            // creamos una variable tipo prepared statement que almacenara un INSERT INTO que debera alamecenar datos 
                                                                                                   // nombre de las columnas
            PreparedStatement pst = cn.prepareStatement("INSERT INTO orden_de_trabajo(Numero_de_placa, tipo_vehiculo, id_cliente, nombe_cliente, telefono_cliente, correo_cliente, tipo_servicio, estado_orden) VALUES(?, ?, ?, ?, ?, ?, ?, ?)");
                                                                            // nombre de la bd(nombre de la tabla) VALUES(tantas ? como columnas)
           // le enviamos el valor de la caje de texto a la columna 1 con un setString
            pst.setString(1, jtfPlacaVehiculo.getText());
            pst.setString(2, (String) jcbTipoVehiculo.getSelectedItem());
            pst.setString(3, jtfIdCliente.getText());
            pst.setString(4, jtfNombreCliente.getText());
            pst.setString(5, jtfTelefonoCliente.getText());
            pst.setString(6, jtfCorreoCliente.getText());
            pst.setString(7, (String) jcbTipoServicio.getSelectedItem());
            pst.setString(8, "Activa");
        
            // el executeUpdate es para  gurdar  bd
        int a=pst.executeUpdate();
            
        if(a>0){
            
           JOptionPane.showMessageDialog(null,"Orden agregada con éxito");
            jtfPlacaVehiculo.setText("");
            jcbTipoVehiculo.setSelectedItem("");
            jtfIdCliente.setText("");
            jtfNombreCliente.setText("");
            jtfTelefonoCliente.setText("");
            jtfCorreoCliente.setText("");
            jcbTipoServicio.setSelectedItem("");
             
        }
        else{
             JOptionPane.showMessageDialog(null,"Error al agregar");
        }
        }catch(Exception e){
            System.err.println(e.toString());
        }        
         
        
        
    }//GEN-LAST:event_jbGenerarOTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrdenDeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrdenDeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrdenDeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrdenDeTrabajo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrdenDeTrabajo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbGenerarOT;
    private javax.swing.JComboBox<String> jcbTipoServicio;
    private javax.swing.JComboBox<String> jcbTipoVehiculo;
    private javax.swing.JTextField jtfCorreoCliente;
    private javax.swing.JTextField jtfIdCliente;
    private javax.swing.JTextField jtfNombreCliente;
    private javax.swing.JTextField jtfPlacaVehiculo;
    private javax.swing.JTextField jtfTelefonoCliente;
    // End of variables declaration//GEN-END:variables
}
